{
    "id": 52,
    "username": "hasanabir72",
    "name": "Hasan Abir",
    "first_name": "Hasan",
    "last_name": "Abir",
    "email": "hasanabir72@gmail.com",
    "url": "https://www.linkedin.com",
    "description": "",
    "link": "https://amorerings.com/author/hasanabir72/",
    "locale": "en_US",
    "nickname": "hasanabir72",
    "slug": "hasanabir72",
    "roles": ["subscriber", "affiliate"],
    "registered_date": "2026-05-22T03:07:33+00:00",
    "capabilities": {
        "read": True,
        "level_0": True,
        "subscriber": True,
        "affiliate": True,
    },
    "extra_capabilities": {"subscriber": True, "affiliate": True},
    "avatar_urls": {
        "24": "https://secure.gravatar.com/avatar/6a7b23c65a9d166ca1eab040c55dbd0973be3d4d02cfb204231294693e20e805?s=24&d=mm&r=g",
        "48": "https://secure.gravatar.com/avatar/6a7b23c65a9d166ca1eab040c55dbd0973be3d4d02cfb204231294693e20e805?s=48&d=mm&r=g",
        "96": "https://secure.gravatar.com/avatar/6a7b23c65a9d166ca1eab040c55dbd0973be3d4d02cfb204231294693e20e805?s=96&d=mm&r=g",
        "128": "https://secure.gravatar.com/avatar/6a7b23c65a9d166ca1eab040c55dbd0973be3d4d02cfb204231294693e20e805?s=128&d=mm&r=g",
    },
    "meta": {
        "persisted_preferences": [],
        "_itsec_primary_dashboard": 0,
        "jetpack_donation_warning_dismissed": False,
    },
    "solid_password_strength": None,
    "solid_last_seen": None,
    "solid_password_changed": "2026-05-22T03:07:33",
    "solid_2fa": None,
    "solid_edit_user_link": "https://amorerings.com/wp-admin/user-edit.php?user_id=52",
    "yoast_head": None,
    "yoast_head_json": None,
    "is_super_admin": False,
    "woocommerce_meta": {
        "variable_product_tour_shown": "",
        "activity_panel_inbox_last_read": "",
        "activity_panel_reviews_last_read": "",
        "categories_report_columns": "",
        "coupons_report_columns": "",
        "customers_report_columns": "",
        "orders_report_columns": "",
        "products_report_columns": "",
        "revenue_report_columns": "",
        "taxes_report_columns": "",
        "variations_report_columns": "",
        "dashboard_sections": "",
        "dashboard_chart_type": "",
        "dashboard_chart_interval": "",
        "dashboard_leaderboard_rows": "",
        "order_attribution_install_banner_dismissed": "",
        "scheduled_updates_promotion_notice_dismissed": "",
        "homepage_layout": "",
        "homepage_stats": "",
        "task_list_tracked_started_tasks": "",
        "android_app_banner_dismissed": "",
        "launch_your_store_tour_hidden": "",
        "coming_soon_banner_dismissed": "",
    },
    "elementor_introduction": "",
    "_links": {
        "self": [
            {
                "href": "https://amorerings.com/wp-json/wp/v2/users/52",
                "targetHints": {"allow": ["GET", "POST", "PUT", "PATCH", "DELETE"]},
            }
        ],
        "collection": [{"href": "https://amorerings.com/wp-json/wp/v2/users"}],
    },
}
