# Generated by Django 6.0.5 on 2026-05-22 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_user_nickname_user_otp_user_profile_picture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='otp_generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='otp',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
