# Generated by Django 6.0.5 on 2026-05-22 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_user_otp_generated_at_alter_user_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='account_type',
            field=models.CharField(choices=[('member', 'Member'), ('VIP', 'VIP'), ('Ambassador', 'Ambassador'), ('fundraiser', 'Fundraiser')], default='member', max_length=20),
        ),
    ]
