# Generated by Django 6.0.5 on 2026-05-23 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_user_account_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpeacialEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('special_event', models.URLField()),
            ],
        ),
    ]
