# Generated by Django 6.0.5 on 2026-05-23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_speacialevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Support',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('how_can_i_help_you', models.TextField(verbose_name='How can I help you?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
