# Generated by Django 6.0.5 on 2026-07-16 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_support'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/'),
        ),
    ]
