# Generated by Django 6.0.5 on 2026-07-22 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_ambassadorslot_ambassadorbooking'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='ambassadorbooking',
            constraint=models.UniqueConstraint(fields=('user',), name='unique_ambassador_booking_per_user'),
        ),
    ]
