# Generated by Django 6.0.5 on 2026-09-01 09:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_ambassadorbooking_unique_ambassador_booking_per_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='RingExchangePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('free_exchange_days', models.PositiveIntegerField(default=14, help_text='Number of days from purchase date during which exchanges are free (if ring is not broken).')),
                ('charge_type', models.CharField(choices=[('fixed', 'Fixed Amount'), ('percentage', 'Percentage of Ring Cost'), ('shipping_only', 'Shipping Cost Only')], default='shipping_only', help_text='How fee is calculated after free exchange window or if ring is broken.', max_length=20)),
                ('fixed_fee_amount', models.PositiveIntegerField(default=0, help_text="Fixed exchange fee amount in cents (e.g. 1500 = $15.00). Used when charge_type='fixed'.")),
                ('fee_percentage', models.DecimalField(decimal_places=2, default=0.0, help_text="Percentage of ring cost (e.g. 20.00 = 20%). Used when charge_type='percentage'.", max_digits=5)),
                ('shipping_cost', models.PositiveIntegerField(default=500, help_text="Flat shipping fee in cents (e.g. 500 = $5.00). Added to fee or used when charge_type='shipping_only'.")),
                ('currency', models.CharField(default='usd', max_length=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Ring Exchange Policy',
                'verbose_name_plural': 'Ring Exchange Policy',
            },
        ),
        migrations.CreateModel(
            name='RingExchangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=100)),
                ('original_item_name', models.CharField(max_length=255)),
                ('original_size', models.CharField(max_length=50)),
                ('desired_size', models.CharField(max_length=50)),
                ('is_damaged', models.BooleanField(default=False, help_text='Check if the ring is broken or damaged.')),
                ('purchase_date', models.DateTimeField()),
                ('original_price', models.PositiveIntegerField(default=0, help_text='Original item price in smallest currency unit (e.g. cents).')),
                ('calculated_fee', models.PositiveIntegerField(default=0, help_text='Calculated exchange fee in cents.')),
                ('shipping_cost', models.PositiveIntegerField(default=0, help_text='Shipping cost portion in cents.')),
                ('total_amount', models.PositiveIntegerField(default=0, help_text='Total charge (fee + shipping) in cents.')),
                ('currency', models.CharField(default='usd', max_length=10)),
                ('is_within_free_window', models.BooleanField(default=True)),
                ('payment_status', models.CharField(choices=[('not_required', 'Not Required'), ('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed')], default='not_required', max_length=20)),
                ('stripe_session_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('stripe_payment_intent_id', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('payment_pending', 'Payment Pending'), ('approved', 'Approved'), ('user_shipped', 'Original Ring Shipped by User'), ('ring_received', 'Original Ring Received by Company'), ('replacement_shipped', 'Replacement Ring Shipped'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=30)),
                ('user_tracking_number', models.CharField(blank=True, max_length=100, null=True)),
                ('replacement_tracking_number', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ring_exchanges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
