# Generated by Django 6.0.5 on 2026-09-01 10:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_ringexchangepolicy_ringexchangerequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='RefundPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refund_deadline_days', models.PositiveIntegerField(default=21, help_text='Number of days from purchase date during which a refund can be requested (default: 21 days).')),
                ('return_shipping_address', models.TextField(default='Amore Rings Returns Dept.\n123 Luxury Lane, Suite 100\nNew York, NY 10001, USA', help_text='Address where customers should mail returned rings.')),
                ('instructions', models.TextField(default='To return your ring for a refund, please package the item securely in its original box and ship it to our returns department. Attach your shipment tracking number to this request once mailed.', help_text='Instructions displayed to customers when requesting a refund.')),
                ('restocking_fee_percentage', models.DecimalField(decimal_places=2, default=0.0, help_text='Optional restocking fee percentage (e.g. 0.00 for no fee).', max_digits=5)),
                ('currency', models.CharField(default='usd', max_length=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Refund Policy',
                'verbose_name_plural': 'Refund Policy',
            },
        ),
        migrations.CreateModel(
            name='RefundRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=100)),
                ('item_name', models.CharField(max_length=255)),
                ('item_size', models.CharField(blank=True, max_length=50, null=True)),
                ('reason', models.TextField()),
                ('purchase_date', models.DateTimeField()),
                ('original_price', models.PositiveIntegerField(default=0, help_text='Original item purchase price in smallest currency unit (e.g. cents).')),
                ('refund_amount', models.PositiveIntegerField(default=0, help_text='Eligible refund amount in cents.')),
                ('currency', models.CharField(default='usd', max_length=10)),
                ('return_deadline', models.DateTimeField()),
                ('is_eligible', models.BooleanField(default=True, help_text='True if request was submitted within the refund deadline window.')),
                ('user_tracking_number', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('ring_shipped', 'Ring Shipped by User'), ('ring_received', 'Ring Received by Company'), ('refund_processed', 'Refund Processed'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='requested', max_length=30)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refund_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
