# Generated by Django 6.0.5 on 2026-09-12 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_refundpolicy_refundrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refundrequest',
            name='original_price',
            field=models.FloatField(default=0, help_text='Original item purchase price in smallest currency unit (e.g. cents).'),
        ),
        migrations.AlterField(
            model_name='refundrequest',
            name='refund_amount',
            field=models.FloatField(default=0, help_text='Eligible refund amount in cents.'),
        ),
    ]
