# Generated by Django 6.0.5 on 2026-09-12 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0012_alter_refundrequest_original_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ringexchangerequest',
            name='original_price',
            field=models.FloatField(default=0, help_text='Original item price.'),
        ),
    ]
